spring:
  datasource:
    url: jdbc:mysql://localhost:3306/routinenyang?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
      show_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_CLIENT_ID}
            client-secret: ${OAUTH2_CLIENT_SECRET}
            scope:
              - email
              - profile
jwt:
  secret-key: ${JWT_SECRET}
  expiration: 86400000 # 1일

springdoc:
  swagger-ui:
    path: /api-test   		# 경로
    url: /api-docs
    tagsSorter: alpha         	# API 그룹 정렬
    operations-sorter: method  	# 엔드포인트 정렬
    persist-authorization: true # 브라우저를 새로고침 하더라도 인증정보 유지
    doc-expansion: none
    display-schema-extensions: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json